export const AUTH_TYPES = {
    OK: "AUTH_OK",
    PIN: "AUTH_PIN",
    PIN_TAN: "AUTH_PIN_TAN",
    PIN_PROTECTORIA_OK: "AUTH_PIN_PROTECTORIA_OK",
    GET_PAYMENT_CARD: "GET_PAYMENT_CARD",
    ENROLLMENT: "ENROLLMENT",
    ENROLLMENT_PROTECTORIA_OK: "ENROLLMENT_PROTECTORIA_OK",
    UNKNOWN: "UNKNOWN",
}